"""empty message

Revision ID: 1bfb58c5c58a
Revises: 20340799f113
Create Date: 2024-04-01 16:21:10.220022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfb58c5c58a'
down_revision = '20340799f113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity_unit', sa.String(length=20), nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('quantity_unit')
        batch_op.drop_column('quantity_value')

    # ### end Alembic commands ###
