"""empty message

Revision ID: 20340799f113
Revises: 9cc9deabe3b0
Create Date: 2024-04-01 15:20:37.255402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20340799f113'
down_revision = '9cc9deabe3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity_unit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('price_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('price_unit', sa.String(length=20), nullable=False))
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('price_unit')
        batch_op.drop_column('price_value')
        batch_op.drop_column('quantity_unit')
        batch_op.drop_column('quantity_value')

    # ### end Alembic commands ###
